"use client";

import {
  Plus,
  FileText,
  Download,
  MoreVertical,
  BookOpen,
  Search,
  Files,
  FileCheck2,
  HardDrive,
  Presentation,
  ChevronDown,
  ArrowUpRight,
  X,
  Trash2,
  Eye,
  Upload,
  CheckCircle2,
  RotateCcw,
  FilePlus2,
} from "lucide-react";
import { useMemo, useState } from "react";

type MaterialType = "PDF" | "PPT";

type Material = {
  id: number;
  title: string;
  subject: string;
  className: string;
  type: MaterialType;
  size: string;
  date: string;
};

const initialMaterials: Material[] = [
  {
    id: 1,
    title: "DBMS Introduction",
    subject: "Database Management Systems",
    className: "BCA 3A",
    type: "PDF",
    size: "2.4 MB",
    date: "Sep 04, 2026",
  },
  {
    id: 2,
    title: "React Fundamentals",
    subject: "Web Development",
    className: "BCA 3B",
    type: "PDF",
    size: "4.1 MB",
    date: "Sep 03, 2026",
  },
  {
    id: 3,
    title: "Introduction to Machine Learning",
    subject: "Data Science",
    className: "BCA 4A",
    type: "PPT",
    size: "6.8 MB",
    date: "Sep 01, 2026",
  },
];

export default function MaterialsPage() {
  const [materials, setMaterials] = useState<Material[]>(initialMaterials);

  const [search, setSearch] = useState("");
  const [typeFilter, setTypeFilter] = useState("All");

  const [showUploadModal, setShowUploadModal] = useState(false);
  const [showMoreMenu, setShowMoreMenu] = useState(false);

  const [selectedMaterial, setSelectedMaterial] =
    useState<Material | null>(null);

  const [openCardMenu, setOpenCardMenu] = useState<number | null>(null);

  const [uploadTitle, setUploadTitle] = useState("");
  const [uploadSubject, setUploadSubject] = useState("");
  const [uploadClass, setUploadClass] = useState("BCA 3A");
  const [uploadType, setUploadType] = useState<MaterialType>("PDF");
  const [uploadSize, setUploadSize] = useState("2.0 MB");
  const [uploadSuccess, setUploadSuccess] = useState(false);

  const filteredMaterials = useMemo(() => {
    const searchValue = search.toLowerCase().trim();

    return materials.filter((material) => {
      const matchesSearch =
        material.title.toLowerCase().includes(searchValue) ||
        material.subject.toLowerCase().includes(searchValue) ||
        material.className.toLowerCase().includes(searchValue);

      const matchesType =
        typeFilter === "All" || material.type === typeFilter;

      return matchesSearch && matchesType;
    });
  }, [materials, search, typeFilter]);

  const totalMaterials = materials.length;

  const pdfCount = materials.filter(
    (material) => material.type === "PDF"
  ).length;

  const pptCount = materials.filter(
    (material) => material.type === "PPT"
  ).length;

  const totalSize = materials.reduce(
    (total, material) =>
      total + parseFloat(material.size.replace(" MB", "")),
    0
  );

  const resetUploadForm = () => {
    setUploadTitle("");
    setUploadSubject("");
    setUploadClass("BCA 3A");
    setUploadType("PDF");
    setUploadSize("2.0 MB");
  };

  const handleUpload = () => {
    if (!uploadTitle.trim() || !uploadSubject.trim()) {
      return;
    }

    const newMaterial: Material = {
      id: Date.now(),
      title: uploadTitle.trim(),
      subject: uploadSubject.trim(),
      className: uploadClass,
      type: uploadType,
      size: uploadSize || "2.0 MB",
      date: new Date().toLocaleDateString("en-US", {
        month: "short",
        day: "2-digit",
        year: "numeric",
      }),
    };

    setMaterials((current) => [newMaterial, ...current]);

    setUploadSuccess(true);

    setTimeout(() => {
      setUploadSuccess(false);
      setShowUploadModal(false);
      resetUploadForm();
    }, 1200);
  };

  const handleDelete = (id: number) => {
    const confirmed = window.confirm(
      "Are you sure you want to remove this learning material?"
    );

    if (!confirmed) return;

    setMaterials((current) =>
      current.filter((material) => material.id !== id)
    );

    setOpenCardMenu(null);

    if (selectedMaterial?.id === id) {
      setSelectedMaterial(null);
    }
  };

  const handleDownload = (material: Material) => {
    const content = `VINEEV EDU - Learning Material

Title: ${material.title}
Subject: ${material.subject}
Class: ${material.className}
Type: ${material.type}
File Size: ${material.size}
Uploaded: ${material.date}

This is a demo downloadable resource generated by the Teacher Dashboard.`;

    const blob = new Blob([content], {
      type: "text/plain;charset=utf-8",
    });

    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");
    link.href = url;
    link.download = `${material.title.replace(/\s+/g, "-")}.txt`;

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    URL.revokeObjectURL(url);

    setOpenCardMenu(null);
  };

  const clearFilters = () => {
    setSearch("");
    setTypeFilter("All");
    setShowMoreMenu(false);
  };

  return (
    <div className="min-h-full bg-gray-50/60 p-6 font-sans antialiased lg:p-8">
      <div className="mx-auto w-full max-w-[1500px]">
        {/* Header */}
        <div className="mb-7 flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between">
          <div>
            <div className="mb-2 flex items-center gap-2">
              <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-indigo-600 shadow-sm shadow-indigo-200">
                <BookOpen size={18} className="text-white" />
              </div>

              <span className="text-xs font-semibold uppercase tracking-wider text-indigo-600">
                Academic Resources
              </span>
            </div>

            <h1 className="text-2xl font-bold tracking-tight text-slate-900">
              Learning Materials
            </h1>

            <p className="mt-1 text-sm font-medium text-slate-500">
              Upload and manage learning resources for your students.
            </p>
          </div>

          <button
            type="button"
            onClick={() => setShowUploadModal(true)}
            className="group inline-flex items-center justify-center gap-2 rounded-xl bg-indigo-600 px-5 py-2.5 text-sm font-semibold text-white shadow-sm shadow-indigo-200 transition duration-200 hover:bg-indigo-700 hover:shadow-md active:scale-[0.98] focus:outline-none focus:ring-2 focus:ring-indigo-300 focus:ring-offset-2"
          >
            <Plus
              size={17}
              className="transition-transform duration-200 group-hover:rotate-90"
            />
            Upload Material
          </button>
        </div>

        {/* KPI Cards */}
        <div className="mb-7 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
          <KpiCard
            title="Total Materials"
            value={totalMaterials}
            description="Learning resources"
            icon={Files}
            iconClass="bg-indigo-50 text-indigo-600"
            hoverClass="hover:border-indigo-200"
          />

          <KpiCard
            title="PDF Documents"
            value={pdfCount}
            description="PDF learning resources"
            icon={FileCheck2}
            iconClass="bg-rose-50 text-rose-600"
            hoverClass="hover:border-rose-200"
          />

          <KpiCard
            title="Presentations"
            value={pptCount}
            description="Presentation materials"
            icon={Presentation}
            iconClass="bg-violet-50 text-violet-600"
            hoverClass="hover:border-violet-200"
          />

          <KpiCard
            title="Storage Used"
            value={`${totalSize.toFixed(1)} MB`}
            description="Total uploaded size"
            icon={HardDrive}
            iconClass="bg-emerald-50 text-emerald-600"
            hoverClass="hover:border-emerald-200"
          />
        </div>

        {/* Main Card */}
        <div className="overflow-visible rounded-xl border border-slate-200 bg-white shadow-sm">
          {/* Toolbar */}
          <div className="border-b border-slate-100 p-4">
            <div className="flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between">
              {/* Search */}
              <div className="relative w-full xl:max-w-md">
                <Search
                  size={17}
                  className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400"
                />

                <input
                  type="text"
                  placeholder="Search materials, classes or subjects..."
                  value={search}
                  onChange={(e) => setSearch(e.target.value)}
                  className="h-10 w-full rounded-lg border border-slate-200 bg-slate-50 pl-10 pr-10 text-sm font-medium text-slate-700 outline-none transition placeholder:text-slate-400 focus:border-indigo-400 focus:bg-white focus:ring-2 focus:ring-indigo-100"
                />

                {search && (
                  <button
                    type="button"
                    onClick={() => setSearch("")}
                    className="absolute right-2.5 top-1/2 flex h-6 w-6 -translate-y-1/2 items-center justify-center rounded-md text-slate-400 transition hover:bg-slate-200 hover:text-slate-700"
                    aria-label="Clear search"
                  >
                    <X size={14} />
                  </button>
                )}
              </div>

              {/* Filters */}
              <div className="flex items-center gap-2">
                <div className="relative">
                  <select
                    value={typeFilter}
                    onChange={(e) => setTypeFilter(e.target.value)}
                    className="h-10 appearance-none rounded-lg border border-slate-200 bg-white pl-3.5 pr-10 text-xs font-semibold text-slate-600 outline-none transition hover:border-slate-300 focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100"
                  >
                    <option value="All">All Types</option>
                    <option value="PDF">PDF</option>
                    <option value="PPT">PPT</option>
                  </select>

                  <ChevronDown
                    size={14}
                    className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-slate-400"
                  />
                </div>

                <div className="relative">
                  <button
                    type="button"
                    onClick={() => setShowMoreMenu((value) => !value)}
                    className="hidden h-10 items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 text-xs font-semibold text-slate-600 transition hover:border-slate-300 hover:bg-slate-50 sm:flex"
                  >
                    <MoreVertical size={16} />
                    More
                  </button>

                  {showMoreMenu && (
                    <div className="absolute right-0 top-12 z-30 w-48 overflow-hidden rounded-xl border border-slate-200 bg-white p-1.5 shadow-lg shadow-slate-200/60">
                      <button
                        type="button"
                        onClick={clearFilters}
                        className="flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-left text-xs font-semibold text-slate-600 transition hover:bg-slate-50 hover:text-indigo-600"
                      >
                        <RotateCcw size={14} />
                        Reset Filters
                      </button>

                      <button
                        type="button"
                        onClick={() => {
                          setTypeFilter("PDF");
                          setShowMoreMenu(false);
                        }}
                        className="flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-left text-xs font-semibold text-slate-600 transition hover:bg-slate-50 hover:text-rose-600"
                      >
                        <FileText size={14} />
                        Show PDF Only
                      </button>

                      <button
                        type="button"
                        onClick={() => {
                          setTypeFilter("PPT");
                          setShowMoreMenu(false);
                        }}
                        className="flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-left text-xs font-semibold text-slate-600 transition hover:bg-slate-50 hover:text-violet-600"
                      >
                        <Presentation size={14} />
                        Show PPT Only
                      </button>
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>

          {/* Section Header */}
          <div className="flex items-center justify-between border-b border-slate-100 px-5 py-4">
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-sm font-bold text-slate-900">
                  Resource Library
                </h2>

                <span className="rounded-full bg-indigo-50 px-2 py-0.5 text-[10px] font-semibold text-indigo-600">
                  {filteredMaterials.length}
                </span>
              </div>

              <p className="mt-0.5 text-xs font-medium text-slate-400">
                {filteredMaterials.length === 0
                  ? "No materials found"
                  : `${filteredMaterials.length} resource${
                      filteredMaterials.length !== 1 ? "s" : ""
                    } available`}
              </p>
            </div>

            <div className="hidden items-center gap-2 text-xs font-medium text-slate-400 md:flex">
              <Files size={14} />
              Course resources
            </div>
          </div>

          {/* Materials Grid */}
          <div className="p-5">
            {filteredMaterials.length > 0 ? (
              <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
                {filteredMaterials.map((material) => (
                  <MaterialCard
                    key={material.id}
                    material={material}
                    openCardMenu={openCardMenu}
                    setOpenCardMenu={setOpenCardMenu}
                    onView={() => {
                      setSelectedMaterial(material);
                      setOpenCardMenu(null);
                    }}
                    onDownload={() => handleDownload(material)}
                    onDelete={() => handleDelete(material.id)}
                  />
                ))}
              </div>
            ) : (
              <div className="py-16 text-center">
                <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-slate-100">
                  <Search size={21} className="text-slate-400" />
                </div>

                <h3 className="mt-4 text-sm font-bold text-slate-800">
                  No materials found
                </h3>

                <p className="mx-auto mt-1 max-w-sm text-xs font-medium leading-5 text-slate-400">
                  Try adjusting your search or file type filter to find the
                  resource you are looking for.
                </p>

                <button
                  type="button"
                  onClick={clearFilters}
                  className="mt-4 inline-flex items-center gap-2 rounded-lg bg-indigo-50 px-3.5 py-2 text-xs font-semibold text-indigo-600 transition hover:bg-indigo-100"
                >
                  <RotateCcw size={13} />
                  Clear Filters
                </button>
              </div>
            )}
          </div>

          {/* Footer */}
          <div className="flex flex-col gap-3 border-t border-slate-100 bg-slate-50/40 px-5 py-3.5 sm:flex-row sm:items-center sm:justify-between">
            <p className="text-[11px] font-medium text-slate-400">
              Showing{" "}
              <span className="font-semibold text-slate-600">
                {filteredMaterials.length}
              </span>{" "}
              of{" "}
              <span className="font-semibold text-slate-600">
                {materials.length}
              </span>{" "}
              materials
            </p>

            <button
              type="button"
              onClick={clearFilters}
              className="group inline-flex items-center gap-1.5 text-[11px] font-semibold text-indigo-600 transition hover:text-indigo-700"
            >
              View all resources
              <ArrowUpRight
                size={13}
                className="transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5"
              />
            </button>
          </div>
        </div>
      </div>

      {/* Upload Modal */}
      {showUploadModal && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4 backdrop-blur-sm"
          onMouseDown={(e) => {
            if (e.target === e.currentTarget) {
              setShowUploadModal(false);
              resetUploadForm();
            }
          }}
        >
          <div className="w-full max-w-lg overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl">
            <div className="flex items-center justify-between border-b border-slate-100 px-6 py-4">
              <div>
                <div className="flex items-center gap-2">
                  <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-indigo-50 text-indigo-600">
                    <FilePlus2 size={18} />
                  </div>

                  <div>
                    <h2 className="text-sm font-bold text-slate-900">
                      Upload Material
                    </h2>
                    <p className="text-[11px] font-medium text-slate-400">
                      Add a new learning resource
                    </p>
                  </div>
                </div>
              </div>

              <button
                type="button"
                onClick={() => {
                  setShowUploadModal(false);
                  resetUploadForm();
                }}
                className="flex h-8 w-8 items-center justify-center rounded-lg text-slate-400 transition hover:bg-slate-100 hover:text-slate-700"
              >
                <X size={17} />
              </button>
            </div>

            <div className="space-y-4 p-6">
              {uploadSuccess ? (
                <div className="flex flex-col items-center justify-center py-10 text-center">
                  <div className="flex h-14 w-14 items-center justify-center rounded-full bg-emerald-50">
                    <CheckCircle2
                      size={28}
                      className="text-emerald-600"
                    />
                  </div>

                  <h3 className="mt-4 text-sm font-bold text-slate-900">
                    Material uploaded successfully
                  </h3>

                  <p className="mt-1 text-xs font-medium text-slate-400">
                    The resource has been added to your library.
                  </p>
                </div>
              ) : (
                <>
                  <div>
                    <label className="mb-1.5 block text-xs font-semibold text-slate-600">
                      Material Title
                    </label>

                    <input
                      value={uploadTitle}
                      onChange={(e) => setUploadTitle(e.target.value)}
                      placeholder="e.g. DBMS Introduction"
                      className="h-10 w-full rounded-lg border border-slate-200 bg-slate-50 px-3.5 text-sm font-medium text-slate-700 outline-none transition placeholder:text-slate-400 focus:border-indigo-400 focus:bg-white focus:ring-2 focus:ring-indigo-100"
                    />
                  </div>

                  <div>
                    <label className="mb-1.5 block text-xs font-semibold text-slate-600">
                      Subject
                    </label>

                    <input
                      value={uploadSubject}
                      onChange={(e) => setUploadSubject(e.target.value)}
                      placeholder="e.g. Database Management Systems"
                      className="h-10 w-full rounded-lg border border-slate-200 bg-slate-50 px-3.5 text-sm font-medium text-slate-700 outline-none transition placeholder:text-slate-400 focus:border-indigo-400 focus:bg-white focus:ring-2 focus:ring-indigo-100"
                    />
                  </div>

                  <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
                    <div>
                      <label className="mb-1.5 block text-xs font-semibold text-slate-600">
                        Class
                      </label>

                      <select
                        value={uploadClass}
                        onChange={(e) => setUploadClass(e.target.value)}
                        className="h-10 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 text-xs font-semibold text-slate-600 outline-none focus:border-indigo-400 focus:bg-white focus:ring-2 focus:ring-indigo-100"
                      >
                        <option>BCA 3A</option>
                        <option>BCA 3B</option>
                        <option>BCA 4A</option>
                        <option>CSIT 5A</option>
                        <option>BIT 2A</option>
                        <option>BCA 6A</option>
                      </select>
                    </div>

                    <div>
                      <label className="mb-1.5 block text-xs font-semibold text-slate-600">
                        Type
                      </label>

                      <select
                        value={uploadType}
                        onChange={(e) =>
                          setUploadType(e.target.value as MaterialType)
                        }
                        className="h-10 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 text-xs font-semibold text-slate-600 outline-none focus:border-indigo-400 focus:bg-white focus:ring-2 focus:ring-indigo-100"
                      >
                        <option value="PDF">PDF</option>
                        <option value="PPT">PPT</option>
                      </select>
                    </div>

                    <div>
                      <label className="mb-1.5 block text-xs font-semibold text-slate-600">
                        Size
                      </label>

                      <input
                        value={uploadSize}
                        onChange={(e) => setUploadSize(e.target.value)}
                        placeholder="2.0 MB"
                        className="h-10 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 text-xs font-semibold text-slate-600 outline-none focus:border-indigo-400 focus:bg-white focus:ring-2 focus:ring-indigo-100"
                      />
                    </div>
                  </div>

                  <div className="rounded-xl border border-dashed border-slate-200 bg-slate-50/70 p-5 text-center">
                    <div className="mx-auto flex h-10 w-10 items-center justify-center rounded-lg bg-white text-indigo-600 shadow-sm">
                      <Upload size={18} />
                    </div>

                    <p className="mt-2 text-xs font-semibold text-slate-700">
                      Resource information
                    </p>

                    <p className="mt-1 text-[11px] font-medium text-slate-400">
                      This demo stores the material information locally.
                    </p>
                  </div>
                </>
              )}
            </div>

            {!uploadSuccess && (
              <div className="flex items-center justify-end gap-2 border-t border-slate-100 bg-slate-50/50 px-6 py-4">
                <button
                  type="button"
                  onClick={() => {
                    setShowUploadModal(false);
                    resetUploadForm();
                  }}
                  className="rounded-lg border border-slate-200 bg-white px-4 py-2 text-xs font-semibold text-slate-600 transition hover:bg-slate-50"
                >
                  Cancel
                </button>

                <button
                  type="button"
                  onClick={handleUpload}
                  disabled={!uploadTitle.trim() || !uploadSubject.trim()}
                  className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2 text-xs font-semibold text-white shadow-sm transition hover:bg-indigo-700 disabled:cursor-not-allowed disabled:opacity-50"
                >
                  <Upload size={14} />
                  Upload Material
                </button>
              </div>
            )}
          </div>
        </div>
      )}

      {/* View Material Modal */}
      {selectedMaterial && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4 backdrop-blur-sm"
          onMouseDown={(e) => {
            if (e.target === e.currentTarget) {
              setSelectedMaterial(null);
            }
          }}
        >
          <div className="w-full max-w-xl overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl">
            <div className="flex items-start justify-between border-b border-slate-100 px-6 py-5">
              <div className="flex items-center gap-3">
                <div
                  className={`flex h-11 w-11 items-center justify-center rounded-xl ${
                    selectedMaterial.type === "PDF"
                      ? "bg-rose-50 text-rose-600"
                      : "bg-violet-50 text-violet-600"
                  }`}
                >
                  {selectedMaterial.type === "PDF" ? (
                    <FileText size={20} />
                  ) : (
                    <Presentation size={20} />
                  )}
                </div>

                <div>
                  <h2 className="max-w-sm text-sm font-bold text-slate-900">
                    {selectedMaterial.title}
                  </h2>

                  <p className="mt-0.5 text-xs font-medium text-slate-400">
                    {selectedMaterial.subject}
                  </p>
                </div>
              </div>

              <button
                type="button"
                onClick={() => setSelectedMaterial(null)}
                className="flex h-8 w-8 items-center justify-center rounded-lg text-slate-400 transition hover:bg-slate-100 hover:text-slate-700"
              >
                <X size={17} />
              </button>
            </div>

            <div className="space-y-4 p-6">
              <div className="rounded-xl border border-slate-200 bg-slate-50/60 p-5">
                <div className="grid grid-cols-2 gap-5">
                  <InfoItem
                    label="Class"
                    value={selectedMaterial.className}
                  />

                  <InfoItem
                    label="File Type"
                    value={selectedMaterial.type}
                  />

                  <InfoItem
                    label="File Size"
                    value={selectedMaterial.size}
                  />

                  <InfoItem
                    label="Uploaded"
                    value={selectedMaterial.date}
                  />
                </div>
              </div>

              <div className="rounded-xl border border-indigo-100 bg-indigo-50/50 p-4">
                <div className="flex gap-3">
                  <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-white text-indigo-600 shadow-sm">
                    <BookOpen size={15} />
                  </div>

                  <div>
                    <p className="text-xs font-bold text-slate-800">
                      Resource Information
                    </p>

                    <p className="mt-1 text-[11px] font-medium leading-5 text-slate-500">
                      This material is available for the selected class and
                      can be downloaded from the resource library.
                    </p>
                  </div>
                </div>
              </div>
            </div>

            <div className="flex items-center justify-end gap-2 border-t border-slate-100 bg-slate-50/50 px-6 py-4">
              <button
                type="button"
                onClick={() => setSelectedMaterial(null)}
                className="rounded-lg border border-slate-200 bg-white px-4 py-2 text-xs font-semibold text-slate-600 transition hover:bg-slate-50"
              >
                Close
              </button>

              <button
                type="button"
                onClick={() => handleDownload(selectedMaterial)}
                className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2 text-xs font-semibold text-white transition hover:bg-indigo-700"
              >
                <Download size={14} />
                Download
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

/* ---------------------------------- */
/* Material Card */
/* ---------------------------------- */

function MaterialCard({
  material,
  openCardMenu,
  setOpenCardMenu,
  onView,
  onDownload,
  onDelete,
}: {
  material: Material;
  openCardMenu: number | null;
  setOpenCardMenu: (id: number | null) => void;
  onView: () => void;
  onDownload: () => void;
  onDelete: () => void;
}) {
  const isPdf = material.type === "PDF";

  return (
    <div className="group relative rounded-xl border border-slate-200 bg-white p-5 shadow-sm transition duration-200 hover:-translate-y-0.5 hover:border-slate-300 hover:shadow-md">
      {/* Top */}
      <div className="flex items-start justify-between">
        <div
          className={`flex h-11 w-11 items-center justify-center rounded-lg ${
            isPdf
              ? "bg-rose-50 text-rose-600"
              : "bg-violet-50 text-violet-600"
          }`}
        >
          {isPdf ? <FileText size={19} /> : <Presentation size={19} />}
        </div>

        <div className="relative">
          <button
            type="button"
            onClick={() =>
              setOpenCardMenu(
                openCardMenu === material.id ? null : material.id
              )
            }
            className="flex h-8 w-8 items-center justify-center rounded-lg text-slate-400 transition hover:bg-slate-100 hover:text-slate-700"
            aria-label={`Actions for ${material.title}`}
          >
            <MoreVertical size={17} />
          </button>

          {openCardMenu === material.id && (
            <div className="absolute right-0 top-9 z-20 w-40 overflow-hidden rounded-xl border border-slate-200 bg-white p-1.5 shadow-lg shadow-slate-200/70">
              <button
                type="button"
                onClick={onView}
                className="flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-left text-xs font-semibold text-slate-600 transition hover:bg-indigo-50 hover:text-indigo-600"
              >
                <Eye size={14} />
                View
              </button>

              <button
                type="button"
                onClick={onDownload}
                className="flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-left text-xs font-semibold text-slate-600 transition hover:bg-emerald-50 hover:text-emerald-600"
              >
                <Download size={14} />
                Download
              </button>

              <div className="my-1 border-t border-slate-100" />

              <button
                type="button"
                onClick={onDelete}
                className="flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-left text-xs font-semibold text-rose-600 transition hover:bg-rose-50"
              >
                <Trash2 size={14} />
                Delete
              </button>
            </div>
          )}
        </div>
      </div>

      {/* Title */}
      <div className="mt-5">
        <div className="flex items-start justify-between gap-3">
          <h2 className="line-clamp-2 text-sm font-bold leading-5 text-slate-800">
            {material.title}
          </h2>

          <span
            className={`shrink-0 rounded-md px-2 py-1 text-[9px] font-bold ${
              isPdf
                ? "bg-rose-50 text-rose-600"
                : "bg-violet-50 text-violet-600"
            }`}
          >
            {material.type}
          </span>
        </div>

        <p className="mt-1.5 line-clamp-1 text-xs font-medium text-slate-400">
          {material.subject}
        </p>
      </div>

      {/* Class */}
      <div className="mt-5 flex items-center gap-2">
        <div className="flex h-7 w-7 items-center justify-center rounded-md bg-slate-100">
          <BookOpen size={14} className="text-slate-500" />
        </div>

        <div>
          <p className="text-[10px] font-medium text-slate-400">Class</p>

          <p className="text-xs font-semibold text-slate-600">
            {material.className}
          </p>
        </div>
      </div>

      {/* Metadata */}
      <div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-4">
        <div>
          <p className="text-[10px] font-medium text-slate-400">
            File size
          </p>

          <p className="mt-0.5 text-[11px] font-semibold text-slate-600">
            {material.size}
          </p>
        </div>

        <div className="text-right">
          <p className="text-[10px] font-medium text-slate-400">
            Uploaded
          </p>

          <p className="mt-0.5 text-[11px] font-semibold text-slate-600">
            {material.date}
          </p>
        </div>
      </div>

      {/* Action */}
      <button
        type="button"
        onClick={onView}
        className="mt-5 flex w-full items-center justify-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-xs font-semibold text-slate-600 transition hover:border-indigo-200 hover:bg-indigo-50 hover:text-indigo-600 active:scale-[0.99]"
      >
        <Eye size={14} />
        View Material
      </button>
    </div>
  );
}

/* ---------------------------------- */
/* KPI Card */
/* ---------------------------------- */

function KpiCard({
  title,
  value,
  description,
  icon: Icon,
  iconClass,
  hoverClass,
}: {
  title: string;
  value: string | number;
  description: string;
  icon: React.ElementType;
  iconClass: string;
  hoverClass: string;
}) {
  return (
    <div
      className={`group relative overflow-hidden rounded-xl border border-slate-200 bg-white p-5 shadow-sm transition duration-200 hover:-translate-y-0.5 hover:shadow-md ${hoverClass}`}
    >
      <div className="flex items-start justify-between gap-4">
        <div className="min-w-0">
          <p className="truncate text-xs font-semibold text-slate-500">
            {title}
          </p>

          <p className="mt-2 text-2xl font-bold tracking-tight text-slate-900">
            {value}
          </p>
        </div>

        <div
          className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-lg ${iconClass}`}
        >
          <Icon size={18} />
        </div>
      </div>

      <p className="mt-4 truncate text-[11px] font-medium text-slate-400">
        {description}
      </p>

      <div className="pointer-events-none absolute -bottom-6 -right-6 h-20 w-20 rounded-full bg-slate-50 opacity-0 transition duration-300 group-hover:opacity-100" />
    </div>
  );
}

/* ---------------------------------- */
/* Info Item */
/* ---------------------------------- */

function InfoItem({
  label,
  value,
}: {
  label: string;
  value: string;
}) {
  return (
    <div>
      <p className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">
        {label}
      </p>

      <p className="mt-1 text-xs font-bold text-slate-700">{value}</p>
    </div>
  );
}